# Лабораторна робота № 3

**Тема:** Бінарні відношення
**Мета:** вивчення властивостей бінарних відношень, операцій над
відношеннями, набуття навичок прийняття рішень на основі заданих відношень.

**Виконав:** студент 321 групи, Ткачук І.В.

## Завдання

### Варіант 6

Перевірити, чи буде дане відношення рефлексивним, антирефлексивним,
симетричним, антисиметричним, асиметричним, транзитивним. Відшукати для
нього найбільший, найменший, максимальний та мінімальний елементи, якщо
такі існують, і побудувати обернене й додаткове відношення.

\begin{equation}
A(R) = \begin{pmatrix}
0 & 1 & 1 & 1 & 0 \\
0 & 1 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 1 & 1 \\
0 & 1 & 0 & 0 & 0 
\end{pmatrix}
\end{equation}


In [14]:
import numpy as np

R = np.array(
    [
        [0, 1, 1, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [0, 1, 0, 0, 0],
    ]
)

R, R.T

(array([[0, 1, 1, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1],
        [0, 1, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0],
        [1, 1, 0, 1, 1],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 1, 0],
        [0, 0, 0, 1, 0]]))

In [15]:
is_reflexive = np.all(np.diag(R) == 1)
is_reflexive

False

In [16]:
is_antireflexive = np.all(np.diag(R) == 0)
is_antireflexive

False

In [17]:
is_symmetric =np.all(R == R.T)
is_symmetric

False

In [18]:
is_antisymmetric = np.all((R & R.T) == np.diag(np.diag(R)))
is_antisymmetric

True

In [19]:
is_assymetric = is_antireflexive and is_antisymmetric
is_assymetric

False

In [20]:
is_transitive = np.all(np.dot(R, R) <= R)
is_transitive

False

In [21]:
largest_element = np.max(R) if R.size else None
smallest_element = np.min(R) if R.size else None

largest_element, smallest_element

(1, 0)

In [22]:
max_element = np.max(R)
min_element = np.min(R)

max_element, min_element

(1, 0)

In [23]:
inverse_relation = R.T
inverse_relation

array([[0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0]])

In [28]:
compliment_relation = np.logical_not(R).astype(int)
compliment_relation

array([[1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 1, 1, 1]])

### Висновок

Дане відношення є антисиметричним, транзитивним. Найбільший елемент - 1, найменший - 0, максимальний - 1, мінімальний - 1. Обернене відношення:

\begin{equation}
A(R^{-1}) = \begin{pmatrix}
0 & 0 & 0 & 0 & 0 \\
1 & 1 & 0 & 0 & 1 \\
1 & 0 & 0 & 1 & 0 \\
1 & 1 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 & 0
\end{pmatrix}
\end{equation}
     
Додаткове відношення:

\begin{equation}
A(\overline{R}) = \begin{pmatrix}
1 & 0 & 0 & 0 & 1 \\
1 & 0 & 1 & 1 & 1 \\
1 & 1 & 1 & 1 & 1 \\
1 & 0 & 0 & 0 & 0 \\
1 & 0 & 1 & 1 & 1
\end{pmatrix}
\end{equation}



### Контрольні питання

1. Дайте визначення бінарного відношення.
2. Які існують способи задання відношень?
3. Яким чином можна задати відношення за допомогою матриці?
4. Як можна задати відношення у вигляді графа?
5. Як задати відношення за допомогою розрізів?
6. Сформулюйте визначення верхнього (нижнього) розрізу відношення.
7. Які із способів задання відношень можна використовувати на
нескінченній множині елементів?
8. Які математичні операції виконують над відношеннями?
9. Яке відношення називається рефлексивним (антирефлексивним)?
10. Яке відношення називається симетричним, антисиметричним,
асиметричним?
11. Які відношення називають транзитивними, сильно транзитивними,
від’ємно транзитивними?
12. Яким чином обчислюють транзитивне замикання відношення?
13. Які властивості характерні для відношення переваги?

14. Дайте визначення найкращого (найгіршого) елемента множини.
15. Який елемент множини називається мінімальним (максимальним) за
даним відношенням переваги?
16. Яке значення в теорії прийняття рішень мають поняття найкращого,
найгіршого, максимального й мінімального елементів? Де вони
використовуються?


#### 1. **Бінарне відношення**

Це підмножина декартового добутку двох множин, яка визначає, як елементи однієї множини відносяться до елементів іншої множини. Формально, якщо $ A $ та $ B $ - множини, бінарне відношення $ R $ з $ A $ в $ B $ є підмножиною множини $ A \times B $.

#### 2. **Способи задання відношень**:

- Переліком пар елементів.
- Використанням матриці відношень.
- Графічним способом (за допомогою графів).
- Заданням розрізів.

#### 3. **Задання відношення за допомогою матриці**:

Матриця відношення - це двовимірний масив, де кожен рядок та стовпець відповідають елементам множини. Якщо відношення виконується між елементами, то відповідна клітина матриці містить 1, інакше - 0.

#### 4. **Задання відношення у вигляді графа**:

Елементи множини представляються як вершини графа, а відношення - як напрямлені ребра між цими вершинами.

#### 5. **Задання відношення за допомогою розрізів**:

Розріз відношення визначається як підмножина множини, для якої всі елементи задовольняють певну умову відносно вибраного елемента в рамках даного відношення.

#### 6. **Визначення верхнього (нижнього) розрізу відношення**:

Верхній розріз відношення для елемента $ x $ включає всі елементи, які пов'язані з $ x $ за цим відношенням. Нижній розріз включає всі елементи, які пов'язуються з $ x $ у зворотному напрямку.

#### 7. **Способи задання відношень на нескінченній множині елементів**:

- Математичні формули або правила.
- Логічні вирази.
- Графи (у певних випадках).

#### 8. **Математичні операції над відношеннями**:

- Об'єднання, перетин, різниця.
- Обернення відношення.
- Композиція відношень.
- Транзитивне замикання.

#### 9. **Рефлексивне та антирефлексивне відношення**:

- Рефлексивне: Відношення $ R $ на множині $ A $ є рефлексивним, якщо кожен елемент $ A $ відноситься до себе.
- Антирефлексивне: Жоден елемент $ A $ не відноситься до себе.

#### 10. **Симетричне, антисиметричне, асиметричне відношення**:

- Симетричне: Якщо $ aRb $ виконується, то і $ bRa $ також виконується.
- Антисиметричне: Якщо $ aRb $ і $ bRa $ виконуються, то $ a = b $.
- Асиметричне: Якщо $ aRb $ виконується, то $ bRa $ не виконується.

#### 11. **Транзитивні, сильно транзитивні, від’ємно транзитивні відношення**:

- Транзитивне: Якщо $ aRb $ і $ bRc $ виконуються, то $ aRc $ також виконується.
- Сильно транзитивне: Якщо $ aRb $ і $ cRd $ виконуються, то або $ aRd $ або $ cRb $ виконується.
- Від’ємно транзитивне: Якщо $ aRb $ не виконується і $ bRc $ не виконується, то $ aRc $ також не виконується.

#### 12. **Обчислення транзитивного замикання відношення**:

Транзитивне замикання відношення можна обчислити, послідовно додаючи елементи до відношення, якщо вони задовольняють умову транзитивності, доки не буде досягнуто стану, коли жодних нових елементів додати не можна.

#### 13. **Властивості відношення переваги**:

- Зазвичай воно є несиметричним або асиметричним.
- Може бути транзитивним.
- В деяких випадках може бути рефлексивним або антирефлексивним.

#### 14. **Найкращий (найгірший) елемент множини**:

- Найкращий елемент - це такий, який переважає всі інші елементи множини за відношенням переваги.
- Найгірший елемент - це такий, який є меншим за всі інші елементи множини за тим же відношенням.

#### 15. **Мінімальний (максимальний) елемент за відношенням переваги**:

- Мінімальний елемент - це такий, перед яким не переважає жоден інший елемент множини.
- Максимальний елемент - це такий, який не переважається жодним іншим елементом множини.

#### 16. **Значення понять найкращого, найгіршого, максимального й мінімального елементів у теорії прийняття рішень**:

- Ці поняття важливі для визначення оптимальних рішень у різних задачах, зокрема в економіці, управлінні, інженерії.
- Вони допомагають визначати кращі або найгірші альтернативи серед набору можливих варіантів.
- Використовуються для аналізу різних варіантів рішень та вибору найбільш підходящих у конкретних ситуаціях.